export function img(unsplashId: string, size = 900): string {
  return `https://images.unsplash.com/photo-${unsplashId}?w=${size}&h=${size}&fit=crop&auto=format&q=80`;
}

export const categoriasSeed = [
  { nombre: "Labiales", slug: "labiales", descripcion: "Labiales de alta pigmentación en fórmulas mate, satinadas y con brillo.", icono: "lipstick", imagenUrl: img("1522335789203-aabd1fc54bc9", 500), orden: 1 },
  { nombre: "Bases", slug: "bases", descripcion: "Bases líquidas y en polvo para un acabado impecable de larga duración.", icono: "droplet", imagenUrl: img("1512496015851-a90fb38ba796", 500), orden: 2 },
  { nombre: "Correctores", slug: "correctores", descripcion: "Correctores de alta cobertura para ojeras e imperfecciones.", icono: "wand", imagenUrl: img("1631730486572-226d1f595b68", 500), orden: 3 },
  { nombre: "Rubores", slug: "rubores", descripcion: "Rubores en polvo y crema para un rubor natural y duradero.", icono: "circle", imagenUrl: img("1516975080664-ed2fc6a32937", 500), orden: 4 },
  { nombre: "Sombras", slug: "sombras", descripcion: "Paletas de sombras multidimensionales para looks de día y de noche.", icono: "palette", imagenUrl: img("1533562389935-457b1ae48a39", 500), orden: 5 },
  { nombre: "Máscaras", slug: "mascaras", descripcion: "Máscaras de pestañas para volumen, curvatura y longitud extrema.", icono: "eye", imagenUrl: img("1547934659-7fa699ef3ce0", 500), orden: 6 },
  { nombre: "Delineadores", slug: "delineadores", descripcion: "Delineadores de precisión en gel, líquido y lápiz.", icono: "pen", imagenUrl: img("1581273154768-0a9a16887d2a", 500), orden: 7 },
  { nombre: "Brochas", slug: "brochas", descripcion: "Sets de brochas profesionales de cerda sintética premium.", icono: "paintbrush", imagenUrl: img("1622336889416-8d790ad807d7", 500), orden: 8 },
  { nombre: "Iluminadores", slug: "iluminadores", descripcion: "Iluminadores líquidos y en polvo para un resplandor multidimensional.", icono: "sun", imagenUrl: img("1583241800698-e8ab01830a07", 500), orden: 9 },
  { nombre: "Polvos", slug: "polvos", descripcion: "Polvos compactos y sueltos para sellar el maquillaje.", icono: "circle-dot", imagenUrl: img("1662751283562-ba2ed2f45855", 500), orden: 10 },
  { nombre: "Skincare", slug: "skincare", descripcion: "Rutina de cuidado facial premium: sueros, hidratantes y protección.", icono: "sparkles", imagenUrl: img("1620916297397-a4a5402a3c6c", 500), orden: 11 },
];

export const marcasSeed = [
  { nombre: "Lumière Paris", slug: "lumiere-paris", descripcion: "Alta cosmética francesa con más de 30 años de trayectoria.", logoUrl: img("1596462502278-27bfdc403348", 200) },
  { nombre: "Velvet Noir", slug: "velvet-noir", descripcion: "Fórmulas de lujo con acabados aterciopelados y pigmentación intensa.", logoUrl: img("1620464003286-a5b0d79f32c2", 200) },
  { nombre: "Rosé Atelier", slug: "rose-atelier", descripcion: "Maquillaje artesanal inspirado en la belleza natural.", logoUrl: img("1625093742435-6fa192b6fb10", 200) },
  { nombre: "Maison Éclat", slug: "maison-eclat", descripcion: "La firma insignia de la casa, edición exclusiva.", logoUrl: img("1596704017254-9b121068fb31", 200) },
  { nombre: "Nova Beauty", slug: "nova-beauty", descripcion: "Cosmética moderna con tecnología de larga duración.", logoUrl: img("1583241800698-e8ab01830a07", 200) },
  { nombre: "Satin & Silk", slug: "satin-silk", descripcion: "Texturas sedosas para una piel de porcelana.", logoUrl: img("1580870069867-74c57ee1bb07", 200) },
  { nombre: "Bloom Cosmetics", slug: "bloom-cosmetics", descripcion: "Color vibrante inspirado en la botánica de lujo.", logoUrl: img("1533562389935-457b1ae48a39", 200) },
  { nombre: "Ombre Luxe", slug: "ombre-luxe", descripcion: "Colección premium de edición limitada.", logoUrl: img("1583241800882-d0087e27c920", 200) },
];

export const promocionesSeed = [
  { nombre: "Venta de Verano", descripcion: "Hasta 25% de descuento en labiales seleccionados.", porcentajeDescuento: 25, diasInicio: -10, diasFin: 20 },
  { nombre: "Black Friday Beauty", descripcion: "30% de descuento en bases e iluminadores.", porcentajeDescuento: 30, diasInicio: -5, diasFin: 15 },
  { nombre: "Skincare Week", descripcion: "20% de descuento en toda la línea skincare.", porcentajeDescuento: 20, diasInicio: -3, diasFin: 10 },
  { nombre: "Edición Especial Ojos", descripcion: "15% de descuento en sombras y delineadores.", porcentajeDescuento: 15, diasInicio: -7, diasFin: 7 },
];

export interface ProductoSeed {
  nombre: string;
  descripcionCorta: string;
  descripcionLarga: string;
  ingredientes: string;
  modoUso: string;
  beneficios: string;
  precio: number;
  categoriaSlug: string;
  marca: string;
  stock: number;
  esNuevo: boolean;
  esEdicionLimitada: boolean;
  imagenes: string[];
  promocion: string | null;
}

export const productosSeed: ProductoSeed[] = [
  { nombre: "Labial Velvet Rouge", descripcionCorta: "Labial mate de larga duración con pigmentación intensa.", descripcionLarga: "El Labial Velvet Rouge ofrece un acabado mate aterciopelado que dura hasta 8 horas sin resecar los labios. Su fórmula enriquecida envuelve el color en una sola pasada.", ingredientes: "Cera de candelilla, vitamina E, pigmentos minerales, aceite de jojoba.", modoUso: "Aplicar directamente desde el centro hacia las comisuras. Para mayor precisión, perfilar antes con delineador de labios.", beneficios: "Larga duración, no reseca, alta pigmentación, acabado mate aterciopelado.", precio: 185, categoriaSlug: "labiales", marca: "Velvet Noir", stock: 40, esNuevo: true, esEdicionLimitada: false, imagenes: ["1522335789203-aabd1fc54bc9", "1596462502278-27bfdc403348"], promocion: "Venta de Verano" },
  { nombre: "Labial Satin Kiss", descripcionCorta: "Labial satinado con efecto húmedo y confort total.", descripcionLarga: "Satin Kiss combina color intenso con una sensación ligera gracias a su base de aceites nutritivos. Ideal para looks de día con un toque luminoso.", ingredientes: "Manteca de karité, aceite de coco, pigmentos encapsulados.", modoUso: "Aplicar sobre labios hidratados. Se puede retocar sin necesidad de desmaquillar previamente.", beneficios: "Hidratación profunda, brillo natural, colores versátiles.", precio: 165, categoriaSlug: "labiales", marca: "Rosé Atelier", stock: 55, esNuevo: false, esEdicionLimitada: false, imagenes: ["1631214499500-2e34edcaccfe"], promocion: null },
  { nombre: "Labial Gloss Diamond", descripcionCorta: "Gloss volumizador con partículas de brillo diamante.", descripcionLarga: "El Gloss Diamond aporta volumen instantáneo y un brillo multidimensional gracias a sus micropartículas reflectantes, sin sensación pegajosa.", ingredientes: "Aceite de almendras, ácido hialurónico, mica perlada.", modoUso: "Aplicar con el aplicador de punta fina sobre labios limpios. Reaplicar según se desee mayor volumen.", beneficios: "Efecto volumen, brillo intenso, no pegajoso.", precio: 145, categoriaSlug: "labiales", marca: "Maison Éclat", stock: 30, esNuevo: false, esEdicionLimitada: true, imagenes: ["1625093742435-6fa192b6fb10"], promocion: null },
  { nombre: "Base HD Perfección Infinita", descripcionCorta: "Base líquida de cobertura completa y acabado natural HD.", descripcionLarga: "Formulada con tecnología de alta definición, esta base difumina imperfecciones y controla el brillo durante todo el día sin obstruir los poros.", ingredientes: "Ácido hialurónico, SPF 15, pigmentos micronizados, extracto de pepino.", modoUso: "Aplicar con brocha o esponja húmeda desde el centro del rostro hacia afuera. Difuminar bien en el contorno de la mandíbula.", beneficios: "Cobertura completa, control de brillo, no comedogénica.", precio: 310, categoriaSlug: "bases", marca: "Lumière Paris", stock: 25, esNuevo: true, esEdicionLimitada: false, imagenes: ["1512496015851-a90fb38ba796", "1598528738936-c50861cc75a9"], promocion: "Black Friday Beauty" },
  { nombre: "Base Velvet Matte 24H", descripcionCorta: "Base mate de larga duración resistente al sudor y la humedad.", descripcionLarga: "Ideal para climas cálidos, esta base ofrece un acabado mate uniforme que se mantiene intacto hasta por 24 horas.", ingredientes: "Polvo de arroz, sílice, óxidos de hierro, extracto de té verde.", modoUso: "Aplicar en capas delgadas con brocha kabuki, dejando secar entre capas para un acabado uniforme.", beneficios: "Resistente al agua, control de grasa, acabado aterciopelado.", precio: 295, categoriaSlug: "bases", marca: "Velvet Noir", stock: 20, esNuevo: false, esEdicionLimitada: false, imagenes: ["1596462502278-27bfdc403348"], promocion: null },
  { nombre: "Base Luminous Skin Tint", descripcionCorta: "Base ligera con acabado luminoso tipo segunda piel.", descripcionLarga: "Esta base sérum aporta cobertura media dejando lucir la piel natural con un resplandor saludable.", ingredientes: "Niacinamida, colágeno vegetal, glicerina, filtros UV.", modoUso: "Aplicar con los dedos o brocha de base en movimientos circulares para integrar con la piel.", beneficios: "Efecto segunda piel, hidratación 12h, luminosidad natural.", precio: 275, categoriaSlug: "bases", marca: "Nova Beauty", stock: 33, esNuevo: true, esEdicionLimitada: false, imagenes: ["1620464003286-a5b0d79f32c2"], promocion: null },
  { nombre: "Corrector Bright Eyes", descripcionCorta: "Corrector iluminador para ojeras y zona periocular.", descripcionLarga: "Su fórmula cremosa neutraliza tonalidades oscuras y aporta luminosidad instantánea sin marcar líneas de expresión.", ingredientes: "Vitamina C, cafeína, mica reflectante, manteca de mango.", modoUso: "Aplicar en forma de triángulo invertido bajo el ojo y difuminar con la yema del dedo o esponja.", beneficios: "Ilumina, no marca líneas, cobertura media a alta.", precio: 135, categoriaSlug: "correctores", marca: "Lumière Paris", stock: 48, esNuevo: false, esEdicionLimitada: false, imagenes: ["1631730486572-226d1f595b68"], promocion: null },
  { nombre: "Corrector Full Coverage Pro", descripcionCorta: "Corrector de cobertura total para imperfecciones y manchas.", descripcionLarga: "Diseñado para camuflar manchas, cicatrices y rojeces con una fórmula de larga duración a prueba de transferencia.", ingredientes: "Óxidos de zinc, dimeticona, pigmentos de alta concentración.", modoUso: "Aplicar con pincel pequeño directamente sobre la imperfección y sellar con polvo translúcido.", beneficios: "Cobertura total, resistente a la transferencia, mate.", precio: 150, categoriaSlug: "correctores", marca: "Satin & Silk", stock: 37, esNuevo: false, esEdicionLimitada: false, imagenes: ["1608979048467-6194dabc6a3d"], promocion: null },
  { nombre: "Rubor Blossom Glow", descripcionCorta: "Rubor en polvo de acabado natural con micro-brillo.", descripcionLarga: "Aporta un rubor saludable con un toque de luminosidad sutil, perfecto para looks frescos y naturales.", ingredientes: "Talco mineral, mica, extracto de flor de cerezo.", modoUso: "Aplicar con brocha angulada sobre los pómulos, difuminando hacia las sienes.", beneficios: "Acabado natural, larga duración, no reseca.", precio: 120, categoriaSlug: "rubores", marca: "Bloom Cosmetics", stock: 60, esNuevo: false, esEdicionLimitada: false, imagenes: ["1516975080664-ed2fc6a32937"], promocion: null },
  { nombre: "Rubor Cream Flush", descripcionCorta: "Rubor en crema multiuso para mejillas y labios.", descripcionLarga: "Su textura cremosa se funde con la piel dejando un rubor translúcido de aspecto muy natural.", ingredientes: "Aceite de jojoba, cera de abejas, pigmentos translúcidos.", modoUso: "Aplicar pequeños puntos en las mejillas y difuminar con los dedos en movimientos circulares.", beneficios: "Multiuso, hidratante, acabado luminoso.", precio: 110, categoriaSlug: "rubores", marca: "Rosé Atelier", stock: 44, esNuevo: true, esEdicionLimitada: false, imagenes: ["1542452255191-c85a98f2c5d1"], promocion: null },
  { nombre: "Paleta Sombras Sunset Muse", descripcionCorta: "Paleta de 12 tonos cálidos con acabados mate y shimmer.", descripcionLarga: "Una paleta versátil con tonos tierra, dorados y cobrizos de alta pigmentación para crear looks de día y noche.", ingredientes: "Talco, mica, dimeticona, pigmentos de alta carga.", modoUso: "Aplicar con brocha de sombras difuminando desde el tono más claro hasta el más oscuro en el pliegue.", beneficios: "Alta pigmentación, larga duración, mezclable.", precio: 245, categoriaSlug: "sombras", marca: "Ombre Luxe", stock: 22, esNuevo: false, esEdicionLimitada: true, imagenes: ["1596704017254-9b121068fb31", "1625093525885-282384697917"], promocion: "Edición Especial Ojos" },
  { nombre: "Paleta Sombras Midnight Velvet", descripcionCorta: "Paleta de 9 tonos oscuros para looks nocturnos dramáticos.", descripcionLarga: "Tonos profundos en acabados mate y metálico diseñados para ahumados intensos y de larga duración.", ingredientes: "Mica, óxidos de hierro, dimeticona, pigmentos perlados.", modoUso: "Aplicar con brocha plana los tonos base y con brocha difuminadora integrar los tonos oscuros en el pliegue.", beneficios: "Pigmentación intensa, mezcla perfecta, sin caída de partículas.", precio: 255, categoriaSlug: "sombras", marca: "Velvet Noir", stock: 18, esNuevo: false, esEdicionLimitada: false, imagenes: ["1533562389935-457b1ae48a39"], promocion: null },
  { nombre: "Máscara Volume Extreme", descripcionCorta: "Máscara de pestañas voluminizadora de efecto dramático.", descripcionLarga: "Su cepillo de cerdas densas multiplica el volumen de las pestañas desde la raíz hasta las puntas.", ingredientes: "Cera de carnauba, polímeros voluminizadores, panthenol.", modoUso: "Aplicar en zigzag desde la raíz, dejar secar 30 segundos y aplicar una segunda capa si se desea mayor volumen.", beneficios: "Volumen extremo, no se cuartea, larga duración.", precio: 140, categoriaSlug: "mascaras", marca: "Nova Beauty", stock: 52, esNuevo: false, esEdicionLimitada: false, imagenes: ["1547934659-7fa699ef3ce0"], promocion: null },
  { nombre: "Máscara Curl & Lift 48H", descripcionCorta: "Máscara curvadora con fijación de curvatura hasta 48 horas.", descripcionLarga: "Combina un cepillo curvo con una fórmula flexible que mantiene la curvatura de las pestañas todo el día.", ingredientes: "Resinas flexibles, biotina, extracto de bambú.", modoUso: "Colocar el cepillo en la base de las pestañas y girar suavemente hacia arriba mientras se desliza hacia las puntas.", beneficios: "Curvatura duradera, alarga, resistente a la humedad.", precio: 150, categoriaSlug: "mascaras", marca: "Lumière Paris", stock: 41, esNuevo: true, esEdicionLimitada: false, imagenes: ["1625094640367-05f84293fe42"], promocion: null },
  { nombre: "Delineador Precision Ink", descripcionCorta: "Delineador líquido de punta ultra fina para trazos precisos.", descripcionLarga: "Su punta flexible de 0.1mm permite crear desde líneas finas hasta el clásico ojo de gato con total control.", ingredientes: "Tinta de alta pigmentación, resinas waterproof, glicerina.", modoUso: "Apoyar la punta cerca de la línea de pestañas y trazar en un solo movimiento continuo.", beneficios: "Trazo preciso, resistente al agua, secado rápido.", precio: 95, categoriaSlug: "delineadores", marca: "Maison Éclat", stock: 65, esNuevo: false, esEdicionLimitada: false, imagenes: ["1581273154768-0a9a16887d2a"], promocion: null },
  { nombre: "Delineador Gel Waterproof", descripcionCorta: "Delineador en gel de larga duración con aplicador de pincel.", descripcionLarga: "Textura cremosa de fácil deslizamiento que se fija en segundos sin perder intensidad de color en todo el día.", ingredientes: "Cera de abejas, pigmentos concentrados, dimeticona.", modoUso: "Aplicar con el pincel biselado siguiendo la línea de las pestañas superiores.", beneficios: "Alta fijación, resistente al agua y al sudor, color intenso.", precio: 105, categoriaSlug: "delineadores", marca: "Satin & Silk", stock: 38, esNuevo: false, esEdicionLimitada: false, imagenes: ["1594903696739-2551e8c2d0f1"], promocion: null },
  { nombre: "Set Brochas Professional 12pz", descripcionCorta: "Set de 12 brochas profesionales de cerda sintética.", descripcionLarga: "Un set completo que cubre cada paso del maquillaje: base, corrector, contorno, sombras y difuminado, con mango ergonómico.", ingredientes: "Cerdas sintéticas veganas, mango de madera lacada, ferrule de aluminio.", modoUso: "Utilizar cada brocha según su función específica indicada en el estuche incluido. Lavar semanalmente con jabón neutro.", beneficios: "Vegano, cerdas suaves, aplicación profesional.", precio: 320, categoriaSlug: "brochas", marca: "Ombre Luxe", stock: 15, esNuevo: false, esEdicionLimitada: true, imagenes: ["1622336889416-8d790ad807d7", "1679623100266-db82be84f5f3"], promocion: null },
  { nombre: "Brocha Kabuki Base Perfecta", descripcionCorta: "Brocha kabuki densa para aplicación de base y polvos.", descripcionLarga: "Su forma abombada y cerdas densas permiten una aplicación uniforme de productos líquidos, en crema y en polvo.", ingredientes: "Cerdas sintéticas de alta densidad, mango compacto.", modoUso: "Aplicar producto en movimientos circulares para difuminar completamente en la piel.", beneficios: "Aplicación uniforme, fácil de limpiar, viaje-friendly.", precio: 85, categoriaSlug: "brochas", marca: "Nova Beauty", stock: 70, esNuevo: false, esEdicionLimitada: false, imagenes: ["1613966802194-d46a163af70d"], promocion: null },
  { nombre: "Iluminador Liquid Glow", descripcionCorta: "Iluminador líquido de acabado húmedo multidimensional.", descripcionLarga: "Unas gotas de este iluminador aportan un resplandor tipo cristal que se puede mezclar con la base o aplicar directamente.", ingredientes: "Mica de grado cosmético, glicerina, extracto de perla.", modoUso: "Mezclar 2-3 gotas con la base o aplicar directamente en los puntos altos del rostro con los dedos.", beneficios: "Brillo multidimensional, mezclable, no granuloso.", precio: 160, categoriaSlug: "iluminadores", marca: "Bloom Cosmetics", stock: 34, esNuevo: true, esEdicionLimitada: false, imagenes: ["1583241800698-e8ab01830a07"], promocion: "Black Friday Beauty" },
  { nombre: "Iluminador en Polvo Diamond Dust", descripcionCorta: "Iluminador compacto en polvo con micro-shimmer.", descripcionLarga: "Un polvo finamente molido que aporta un brillo tipo diamante sin dejar partículas gruesas sobre la piel.", ingredientes: "Mica, talco, sílice, pigmentos perlados.", modoUso: "Aplicar con brocha en abanico sobre pómulos, puente nasal y arco de cupido.", beneficios: "Brillo fino, larga duración, look profesional.", precio: 145, categoriaSlug: "iluminadores", marca: "Velvet Noir", stock: 29, esNuevo: false, esEdicionLimitada: false, imagenes: ["1583241800882-d0087e27c920"], promocion: null },
  { nombre: "Polvo Compacto Matte Finish", descripcionCorta: "Polvo compacto translúcido para sellar el maquillaje.", descripcionLarga: "Controla el brillo y prolonga la duración del maquillaje sin alterar el tono de la base ni resecar la piel.", ingredientes: "Sílice, almidón de maíz, talco mineral.", modoUso: "Aplicar con esponja compacta presionando suavemente sobre las zonas con más brillo.", beneficios: "Control de brillo, acabado natural, no reseca.", precio: 98, categoriaSlug: "polvos", marca: "Lumière Paris", stock: 58, esNuevo: false, esEdicionLimitada: false, imagenes: ["1662751283562-ba2ed2f45855"], promocion: null },
  { nombre: "Polvo Suelto HD Setting", descripcionCorta: "Polvo suelto de fijación con efecto suave enfoque.", descripcionLarga: "Su textura ultrafina difumina líneas de expresión y poros, dejando un acabado tipo filtro en fotografías.", ingredientes: "Polvo de arroz, sílice esferificada, extracto de lavanda.", modoUso: "Aplicar con brocha grande en movimientos de sellado sobre toda la cara.", beneficios: "Efecto desenfoque, larga duración, ultrafino.", precio: 115, categoriaSlug: "polvos", marca: "Maison Éclat", stock: 46, esNuevo: false, esEdicionLimitada: false, imagenes: ["1704621354138-e124277356f2"], promocion: null },
  { nombre: "Sérum Vitamina C Radiance", descripcionCorta: "Sérum facial iluminador con vitamina C estabilizada.", descripcionLarga: "Combate el estrés oxidativo y unifica el tono de la piel, aportando luminosidad desde la primera aplicación.", ingredientes: "Vitamina C 15%, ácido ferúlico, vitamina E, ácido hialurónico.", modoUso: "Aplicar 3-4 gotas sobre rostro limpio por la mañana antes del protector solar.", beneficios: "Ilumina, antioxidante, unifica el tono.", precio: 220, categoriaSlug: "skincare", marca: "Nova Beauty", stock: 40, esNuevo: true, esEdicionLimitada: false, imagenes: ["1620916297397-a4a5402a3c6c", "1585945037805-5fd82c2e60b1"], promocion: "Skincare Week" },
  { nombre: "Crema Hidratante 24H Barrier", descripcionCorta: "Crema facial hidratante que refuerza la barrera cutánea.", descripcionLarga: "Fórmula rica en ceramidas que restaura la barrera de hidratación natural de la piel durante 24 horas.", ingredientes: "Ceramidas, niacinamida, manteca de karité, escualano.", modoUso: "Aplicar mañana y noche sobre rostro y cuello con movimientos ascendentes.", beneficios: "Hidratación 24h, repara la barrera cutánea, no comedogénica.", precio: 195, categoriaSlug: "skincare", marca: "Satin & Silk", stock: 36, esNuevo: false, esEdicionLimitada: false, imagenes: ["1608571423902-eed4a5ad8108"], promocion: null },
  { nombre: "Protector Solar Invisible SPF50", descripcionCorta: "Protector solar facial de acabado invisible sin residuo blanco.", descripcionLarga: "Protección de amplio espectro con textura ligera que se absorbe rápidamente y funciona como base para el maquillaje.", ingredientes: "Filtros UV de amplio espectro, niacinamida, extracto de té verde.", modoUso: "Aplicar generosamente como último paso de la rutina matutina, reaplicar cada 3-4 horas de exposición solar.", beneficios: "SPF50, acabado invisible, base para maquillaje.", precio: 175, categoriaSlug: "skincare", marca: "Rosé Atelier", stock: 50, esNuevo: true, esEdicionLimitada: false, imagenes: ["1620916566398-39f1143ab7be"], promocion: null },
  { nombre: "Sérum Ácido Hialurónico Plump", descripcionCorta: "Sérum de hidratación profunda con ácido hialurónico multipeso.", descripcionLarga: "Combina moléculas de distinto peso molecular para hidratar en múltiples capas de la piel, aportando volumen y firmeza.", ingredientes: "Ácido hialurónico multipeso, glicerina, aloe vera.", modoUso: "Aplicar sobre piel húmeda para potenciar la absorción, seguir con crema hidratante.", beneficios: "Hidratación profunda, efecto plump, apto para piel sensible.", precio: 210, categoriaSlug: "skincare", marca: "Lumière Paris", stock: 31, esNuevo: false, esEdicionLimitada: false, imagenes: ["1629198688000-71f23e745b6e"], promocion: null },
  { nombre: "Contorno de Ojos Renew", descripcionCorta: "Contorno de ojos antiedad con péptidos y cafeína.", descripcionLarga: "Reduce la apariencia de ojeras y líneas de expresión en la delicada zona periocular con uso constante.", ingredientes: "Cafeína, péptidos de colágeno, vitamina K, manteca de karité.", modoUso: "Aplicar una pequeña cantidad con el aplicador de metal en movimientos de golpeteo suave.", beneficios: "Reduce ojeras, antiedad, efecto frío relajante.", precio: 185, categoriaSlug: "skincare", marca: "Bloom Cosmetics", stock: 27, esNuevo: false, esEdicionLimitada: true, imagenes: ["1567721913486-6585f069b332"], promocion: null },
  { nombre: "Labial Liquid Matte Extreme", descripcionCorta: "Labial líquido mate de fijación extrema todo el día.", descripcionLarga: "Fórmula transferproof con un aplicador de precisión que ofrece un mate perfecto sin resecar los labios.", ingredientes: "Polímeros filmógenos, aceite de argán, vitamina E.", modoUso: "Aplicar desde el centro hacia las comisuras y dejar secar 60 segundos sin frotar los labios.", beneficios: "Transferproof, mate extremo, hidratante.", precio: 170, categoriaSlug: "labiales", marca: "Ombre Luxe", stock: 42, esNuevo: false, esEdicionLimitada: false, imagenes: ["1555050455-f96634b5cba6"], promocion: null },
  { nombre: "Base Cushion Glow Compact", descripcionCorta: "Base cushion compacta de aplicación rápida con esponja incluida.", descripcionLarga: "Práctica y de fácil retoque, esta base cushion aporta cobertura media con un acabado luminoso natural.", ingredientes: "Colágeno, extracto de perla, filtros UV.", modoUso: "Presionar la esponja sobre el disco de producto y aplicar con toques suaves sobre el rostro.", beneficios: "Práctico, retocable, acabado luminoso.", precio: 265, categoriaSlug: "bases", marca: "Nova Beauty", stock: 24, esNuevo: true, esEdicionLimitada: false, imagenes: ["1617422275558-e5f616302690"], promocion: null },
  { nombre: "Paleta Rubor & Iluminador Duo", descripcionCorta: "Paleta dúo de rubor e iluminador en tonos rosados.", descripcionLarga: "Combina un rubor aterciopelado con un iluminador perlado para un efecto mejillas saludables en un solo paso.", ingredientes: "Mica, talco, extracto de rosa mosqueta.", modoUso: "Aplicar el rubor en el centro de las mejillas y el iluminador en los puntos altos del rostro.", beneficios: "2 en 1, mezclable, tonos universales.", precio: 155, categoriaSlug: "rubores", marca: "Rosé Atelier", stock: 39, esNuevo: false, esEdicionLimitada: false, imagenes: ["1613255348289-1407e4f2f980"], promocion: null },
  { nombre: "Sombra Individual Metallic Foil", descripcionCorta: "Sombra individual de acabado metálico foil de alto impacto.", descripcionLarga: "Un solo toque de esta sombra cremosa aporta un acabado metálico intenso ideal para looks de fiesta.", ingredientes: "Mica de alto brillo, dimeticona, pigmentos metálicos.", modoUso: "Aplicar con el dedo o brocha plana húmeda para potenciar el efecto metálico.", beneficios: "Alto impacto, aplicación sencilla, no se cae.", precio: 75, categoriaSlug: "sombras", marca: "Velvet Noir", stock: 48, esNuevo: false, esEdicionLimitada: false, imagenes: ["1571646034647-52e6ea84b28c"], promocion: null },
  { nombre: "Brocha Difuminadora Sombras Pro", descripcionCorta: "Brocha difuminadora de cerdas suaves para mezcla perfecta.", descripcionLarga: "Diseñada para difuminar sombras y crear transiciones de color perfectas sin líneas marcadas.", ingredientes: "Cerdas sintéticas ultrasuaves, mango largo balanceado.", modoUso: "Utilizar en movimientos de vaivén en el pliegue del párpado para difuminar los tonos.", beneficios: "Difuminado perfecto, cerdas suaves, uso profesional.", precio: 65, categoriaSlug: "brochas", marca: "Maison Éclat", stock: 55, esNuevo: false, esEdicionLimitada: false, imagenes: ["1526045478516-99145907023c"], promocion: null },
  { nombre: "Mascarilla Facial Detox Clay", descripcionCorta: "Mascarilla de arcilla purificante para piel mixta y grasa.", descripcionLarga: "Absorbe el exceso de grasa y minimiza la apariencia de los poros dejando la piel visiblemente más limpia.", ingredientes: "Arcilla caolín, carbón activado, extracto de árbol de té.", modoUso: "Aplicar una capa uniforme sobre rostro limpio, dejar actuar 10 minutos y retirar con agua tibia.", beneficios: "Purifica, minimiza poros, controla la grasa.", precio: 125, categoriaSlug: "skincare", marca: "Velvet Noir", stock: 45, esNuevo: false, esEdicionLimitada: false, imagenes: ["1616750819456-5cdee9b85d22"], promocion: null },
];

export const bannersSeed = [
  { titulo: "Belleza que se define en ti", subtitulo: "Descubre la nueva colección de alta cosmética Èclat", imagenUrl: img("1512496015851-a90fb38ba796", 1600), textoBotonPrimario: "Comprar ahora", urlBotonPrimario: "/catalogo", orden: 1 },
  { titulo: "Edición Limitada Midnight", subtitulo: "Tonos intensos para looks inolvidables", imagenUrl: img("1533562389935-457b1ae48a39", 1600), textoBotonPrimario: "Descubrir", urlBotonPrimario: "/catalogo?categoria=sombras", orden: 2 },
  { titulo: "Skincare que transforma", subtitulo: "Rutinas premium para una piel radiante", imagenUrl: img("1580870069867-74c57ee1bb07", 1600), textoBotonPrimario: "Explorar skincare", urlBotonPrimario: "/catalogo?categoria=skincare", orden: 3 },
  { titulo: "Hasta 30% de descuento", subtitulo: "En productos seleccionados por tiempo limitado", imagenUrl: img("1583241800698-e8ab01830a07", 1600), textoBotonPrimario: "Ver ofertas", urlBotonPrimario: "/catalogo?oferta=true", orden: 4 },
];
